export const todos = [
    {
        id: 1,
        title: "get milk",
        body:"Sit sit ex ut cillum ex cillum sit veniam voluptate pariatur eu est veniam qui. Cupidatat labore nisi sunt voluptate exercitation nostrud qui ullamco exercitation dolor commodo amet qui. Incididunt ea ad elit est deserunt duis non aliquip aute. Culpa exercitation excepteur sunt occaecat et Lorem sint incididunt excepteur adipisicing sit Lorem laboris. Anim ex ut laborum Lorem est irure quis fugiat eu elit aliquip cupidatat.",
        created: "10:00 am jul,02,2022",
        updated: "09:05 pm jul,12,2022",
        done: false,
        ended: "",
    },
    {
        id: 2,
        title: "get milk",
        body:"Sit sit ex ut cillum ex cillum sit veniam voluptate pariatur eu est veniam qui. Cupidatat labore nisi sunt voluptate exercitation nostrud qui ullamco exercitation dolor commodo amet qui. Incididunt ea ad elit est deserunt duis non aliquip aute. Culpa exercitation excepteur sunt occaecat et Lorem sint incididunt excepteur adipisicing sit Lorem laboris. Anim ex ut laborum Lorem est irure quis fugiat eu elit aliquip cupidatat.",
        created: "10:00 am jul,02,2022",
        updated: "09:05 pm jul,12,2022",
        done: true,
        ended: "09:05 pm jul,12,2022",
    },
    {
        id: 3,
        title: "get milk",
        body:"Sit sit ex ut cillum ex cillum sit veniam voluptate pariatur eu est veniam qui. Cupidatat labore nisi sunt voluptate exercitation nostrud qui ullamco exercitation dolor commodo amet qui. Incididunt ea ad elit est deserunt duis non aliquip aute. Culpa exercitation excepteur sunt occaecat et Lorem sint incididunt excepteur adipisicing sit Lorem laboris. Anim ex ut laborum Lorem est irure quis fugiat eu elit aliquip cupidatat.",
        created: "10:00 am jul,02,2022",
        updated: "09:05 pm jul,12,2022",
        done: false,
        ended: "",
    },
    {
        id: 4,
        title: "get milk",
        body:"Sit sit ex ut cillum ex cillum sit veniam voluptate pariatur eu est veniam qui. Cupidatat labore nisi sunt voluptate exercitation nostrud qui ullamco exercitation dolor commodo amet qui. Incididunt ea ad elit est deserunt duis non aliquip aute. Culpa exercitation excepteur sunt occaecat et Lorem sint incididunt excepteur adipisicing sit Lorem laboris. Anim ex ut laborum Lorem est irure quis fugiat eu elit aliquip cupidatat.",
        created: "10:00 am jul,02,2022",
        updated: "09:05 pm jul,12,2022",
        done: true,
        ended: "09:05 pm jul,12,2022",
    },
    {
        id: 5,
        title: "get milk",
        body:"Sit sit ex ut cillum ex cillum sit veniam voluptate pariatur eu est veniam qui. Cupidatat labore nisi sunt voluptate exercitation nostrud qui ullamco exercitation dolor commodo amet qui. Incididunt ea ad elit est deserunt duis non aliquip aute. Culpa exercitation excepteur sunt occaecat et Lorem sint incididunt excepteur adipisicing sit Lorem laboris. Anim ex ut laborum Lorem est irure quis fugiat eu elit aliquip cupidatat.",
        created: "10:00 am jul,02,2022",
        updated: "09:05 pm jul,12,2022",
        done: false,
        ended: "",
    },
    {
        id: 6,
        title: "get milk",
        body:"Sit sit ex ut cillum ex cillum sit veniam voluptate pariatur eu est veniam qui. Cupidatat labore nisi sunt voluptate exercitation nostrud qui ullamco exercitation dolor commodo amet qui. Incididunt ea ad elit est deserunt duis non aliquip aute. Culpa exercitation excepteur sunt occaecat et Lorem sint incididunt excepteur adipisicing sit Lorem laboris. Anim ex ut laborum Lorem est irure quis fugiat eu elit aliquip cupidatat.",
        created: "10:00 am jul,02,2022",
        updated: "09:05 pm jul,12,2022",
        done: true,
        ended: "09:05 pm jul,12,2022",
    },
    
];